name: Deploy Angular App
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build --prod
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fetch S3 bucket name
        id: fetch-bucket
        run: |
          bucket_arn=$(aws resourcegroupstaggingapi get-resources \
            --tag-filters Key=Name,Values=dtq-frontend Key=Environment,Values=production Key=Project,Values=DTQ \
            --resource-type-filters s3 \
            --query 'ResourceTagMappingList[0].ResourceARN' \
            --output text)
          bucket_name=$(echo "$bucket_arn" | cut -d':' -f6)
          echo "bucket_name=$bucket_name" >> $GITHUB_ENV
          
      - name: Deploy to S3
        run: |
          aws s3 sync dist/dtq-ng/browser "s3://$bucket_name/" --delete
        
      - name: Invalidate CloudFront (if using CloudFront)
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
